version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  app:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  data: